### ISSUE TITLE
short work plan 1

### ISSUE THREAD

**Issue by MakedonskyLF** [MakedonskyLF/spectreCreator#1]
- [ ] make nuclide class
- [ ] function for linear spectr (activity, nuclides)
- [ ] smoothing function, graduation generation of histogram
- [ ] efficiency accounting
- [ ] exporting spectr
